language: ruby
rvm:
  - 2.1.0
  - 2.1.2
  - ruby-head
before_script:
  - /bin/cp $TRAVIS_BUILD_DIR/config/initializers/secret_token.rb.example $TRAVIS_BUILD_DIR/config/initializers/secret_token.rb
  - /bin/cp $TRAVIS_BUILD_DIR/config/initializers/portal_configuration.rb.example $TRAVIS_BUILD_DIR/config/initializers/portal_configuration.rb
  - RAILS_ENV=test bundle exec rake db:schema:load
script:
  - bundle exec rake test
matrix:
  allow_failures:
    - rvm: ruby-head
